{
  "os": "linux",
  "dist": "trusty",
  "group": "stable",
  "script": [
    (npm test)
  ],
  "install": [
    "(npm install)"
  ],
  "node_js": "9.8.0",
  "language": "node_js",
  "before_install": [
    "nvm install 9.8.0",
    "nvm use 9.8.0",
    "npm install -g jest@^23.5.0"
  ]
}
