export const SET_SEARCHING = 'SET_SEARCHING'; 
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'; 
export const SET_SEARCH_ERROR = 'SET_SEARCH_ERROR';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
