export const ADD_USER_VISUALIZATIONS = 'ADD_USER_VISUALIZATIONS';
export const SET_USER_VISUALIZATIONS = 'SET_USER_VISUALIZATIONS';
export const SET_FETCHING_VISUALIZATION = 'SET_FETCHING_VISUALIZATION';
export const SET_VISUALIZATIONS_ERROR = 'SET_VISUALIZATIONS_ERROR';
export const REMOVE_VISUALIZATIONS = 'REMOVE_VISUALIZATIONS'